### ISSUE TITLE
Signup error [TypeError: Network request failed]

### ISSUE THREAD

**Issue by vicnala** [trustlessCapital/tcap-mobile#22]
Hi,

I'm trying to run the code on Android and I get this error.
It seems the Android App can't reach the api and I can't find the reason.

Can you help, please?

**Comment by lmahanand** [comment]
Hello @vicnala Thank you for trying out the android app. Backend API calls will not work at the moment since they are protected by AWS API Keys. 

We will soon be removing the api key check and allow them to be accessed (With rate limit) by anyone.

**Comment by vicnala** [comment]
Hi @lmahanand!,

Ok. I've tried to reach the API by using node and the node-fetch package.

By using this file:
https://github.com/trustlessCapital/tcap-mobile/blob/master/src/%40Services/api-services.js
And the file imported by the above:
https://github.com/trustlessCapital/tcap-mobile/blob/master/src/%40Config/default.js

I can call the function `singIn` and I have a response like this:
```js
{
  id: 'f67edcdb-40ce-441c-8d67-7ef7195d6d23',
  email: 'vicnala@xxxxxx.com',
  phoneNumber: '+XXYYYYYYYY',
  status: 'active',
  isPhoneVerified: false,
  isEmailVerified: false,
  isMnemonicCreated: false,
  isAccountUnlocked: false,
  lastLoginAt: '2020-12-10T08:58:26.000Z',
  walletAddress: null,
  privateKeyAddress: null,
  futureAddress: null,
  createdAt: '2020-12-10T08:58:33.008Z',
  updatedAt: '2020-12-10T08:58:33.008Z'
}
```

So I think the API is working...

But it does't when using fetch in the Android App because it throws the "TypeError: Network request failed" error.

Thanks!

**Comment by Sukumar-Abhijeet** [comment]
@vicnala Thanks for raising this error.
However it seems you are running debug mode in android.
So you can just do a simple thing to get it running
https://github.com/trustlessCapital/tcap-mobile/blob/master/src/%40Config/default.js
Open this default.js file in your code editor and change 
const setEnv = env !== 'development';        to        const setEnv = env === 'development';

This will get your error fixed!.
However we are planning to rate limit the apis, hence we have expired the SECURE_KEY present in the config.
Will soon update the repo with a development SECURE_KEY,  After that you can use it.

Feel free to open this issue again if you face any problem after we update the SECURE_KEY for development

**Comment by vicnala** [comment]
Hi @Sukumar-Abhijeet!

Thank you!

I'm going to email you to hello@trustless.capital to tell you our plans.
